export type Setting =
  | 'Business'
  | 'Casual'
  | 'Formal'
  | 'Sportswear'
  | 'Lingerie';
export type ClothingType =
  | 'Clothing'
  | 'Accessory'
  | 'Footwear'
  | 'Undergarments';
export type ClothingSubType =
  | 'T-Shirt'
  | 'Top'
  | 'Dress'
  | 'Skirt'
  | 'Shirt'
  | 'Pants'
  | 'Shorts'
  | 'Sweater'
  | 'Corset'
  | 'Jacket'
  | 'Jeans'
  | 'Miniskirt'
  | 'Apron';
export type AccessoriesSubType =
  | 'Anklet'
  | 'Belt'
  | 'Bangles and Bracelets'
  | 'Brooches and Pins'
  | 'Cuff Links and Studs'
  | 'Earrings'
  | 'Eyeglasses'
  | 'Facemask'
  | 'Gloves'
  | 'Handbags'
  | 'Headdresses and headwraps'
  | 'Hat'
  | 'Hair Accessory'
  | 'Helmet'
  | 'Handkerchiefs and pocket squares'
  | 'Luggage'
  | 'Necklace'
  | 'Necktie'
  | 'Purse'
  | 'Wallet'
  | 'Ring'
  | 'Sash'
  | 'Scarf'
  | 'Sunglasses'
  | 'Umbrella'
  | 'Veil'
  | 'Watch';
export type FootwearSubType =
  | 'Chukka boots'
  | 'Combat boots'
  | 'Cowboy boots'
  | 'Derby boots'
  | 'Fashion boots'
  | 'Go-go boots'
  | 'Hiking boots'
  | 'Motorcycle boots'
  | 'Mukluk'
  | 'Platform boots'
  | 'Riding boots'
  | 'Russian boots'
  | 'Seaboots'
  | 'Tabi boots'
  | 'Tanker boots'
  | 'Thigh-high boots'
  | 'Valenki'
  | 'Veldskoen'
  | 'Waders'
  | 'Wellington boots'
  | 'Winklepickers'
  | 'Sneakers'
  | 'Ballet flats'
  | 'Brothel creepers'
  | 'Court shoes'
  | 'Diabetic shoes'
  | 'Espadrilles'
  | 'Galoshes'
  | 'Kitten heels'
  | 'Derby shoes'
  | 'Oxford shoes'
  | 'Brogues'
  | 'Blucher shoes'
  | 'High-tops'
  | 'Loafers'
  | 'Mary Janes'
  | 'Moccasins'
  | 'Monks'
  | 'Mules'
  | 'Platform shoes'
  | 'Plimsoll shoes'
  | 'School shoes'
  | 'Skate shoes'
  | 'Tap shoes'
  | 'Toe shoes'
  | 'Sandals'
  | 'Kolhapuri Chappals'
  | 'Peshawari chappal'
  | 'Flip-flops'
  | 'Slide'
  | 'Wörishofer'
  | 'Avarca'
  | 'Slippers'
  | 'Ballet shoes'
  | 'Boat shoes'
  | 'High-heeled footwear'
  | 'Sailing boots'
  | 'Ski boots'
  | 'Pointe shoes';
export type UndergarmentsSubType =
  | 'Bloomers'
  | 'Body tights'
  | 'Bodysuit'
  | 'Bra'
  | 'Bustier '
  | 'Camisole'
  | 'Chemise'
  | 'Garter belt'
  | 'Leggings'
  | 'Petticoat'
  | 'Shapers '
  | 'Socks'
  | 'Stockings'
  | 'Teddy'
  | 'Tights'
  | 'Undershirt'
  | 'Underwear';
